#%RAML 0.8
title: IBM i Program Call API
version: 1.0.0

schemas:
  - orderRequest: !include schemas/orderRequestSchema.json
  - orderResponse: !include schemas/orderResponseSchema.json
    
/orders:
  post:
    body: 
      application/json:
        schema: orderRequest
        example: !include examples/orderRequest.json
    responses: 
      200:
        body: 
          application/json:
            schema: orderResponse
            example: !include examples/orderResponse.json